//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HockeyScoreboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:30")]
        public global::System.TimeSpan TimeoutDuration {
            get {
                return ((global::System.TimeSpan)(this["TimeoutDuration"]));
            }
            set {
                this["TimeoutDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan BreakDuration {
            get {
                return ((global::System.TimeSpan)(this["BreakDuration"]));
            }
            set {
                this["BreakDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:07:00")]
        public global::System.TimeSpan PeriodPresetA {
            get {
                return ((global::System.TimeSpan)(this["PeriodPresetA"]));
            }
            set {
                this["PeriodPresetA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan PeriodPresetB {
            get {
                return ((global::System.TimeSpan)(this["PeriodPresetB"]));
            }
            set {
                this["PeriodPresetB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan PeriodPresetC {
            get {
                return ((global::System.TimeSpan)(this["PeriodPresetC"]));
            }
            set {
                this["PeriodPresetC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:00")]
        public global::System.TimeSpan PeriodPresetD {
            get {
                return ((global::System.TimeSpan)(this["PeriodPresetD"]));
            }
            set {
                this["PeriodPresetD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan PenaltyTimePresetA {
            get {
                return ((global::System.TimeSpan)(this["PenaltyTimePresetA"]));
            }
            set {
                this["PenaltyTimePresetA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:02:00")]
        public global::System.TimeSpan PenaltyTimePresetB {
            get {
                return ((global::System.TimeSpan)(this["PenaltyTimePresetB"]));
            }
            set {
                this["PenaltyTimePresetB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan PenaltyTimePresetC {
            get {
                return ((global::System.TimeSpan)(this["PenaltyTimePresetC"]));
            }
            set {
                this["PenaltyTimePresetC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan PenaltyTimePresetD {
            get {
                return ((global::System.TimeSpan)(this["PenaltyTimePresetD"]));
            }
            set {
                this["PenaltyTimePresetD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsedTeamDirectory {
            get {
                return ((string)(this["UsedTeamDirectory"]));
            }
            set {
                this["UsedTeamDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51, 51, 51")]
        public global::System.Drawing.Color ColorBackgroundMain {
            get {
                return ((global::System.Drawing.Color)(this["ColorBackgroundMain"]));
            }
            set {
                this["ColorBackgroundMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("77, 79, 95")]
        public global::System.Drawing.Color ColorBackgroundSecondary {
            get {
                return ((global::System.Drawing.Color)(this["ColorBackgroundSecondary"]));
            }
            set {
                this["ColorBackgroundSecondary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorBorderBrush {
            get {
                return ((global::System.Drawing.Color)(this["ColorBorderBrush"]));
            }
            set {
                this["ColorBorderBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ColorPenaltyIndicatorFree {
            get {
                return ((global::System.Drawing.Color)(this["ColorPenaltyIndicatorFree"]));
            }
            set {
                this["ColorPenaltyIndicatorFree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorPenaltyIndicatorOccupied {
            get {
                return ((global::System.Drawing.Color)(this["ColorPenaltyIndicatorOccupied"]));
            }
            set {
                this["ColorPenaltyIndicatorOccupied"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorTextMain {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextMain"]));
            }
            set {
                this["ColorTextMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("241, 205, 70")]
        public global::System.Drawing.Color ColorTextValues {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextValues"]));
            }
            set {
                this["ColorTextValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238, 69, 92")]
        public global::System.Drawing.Color ColorTextTime {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextTime"]));
            }
            set {
                this["ColorTextTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color ColorTextPeriod {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextPeriod"]));
            }
            set {
                this["ColorTextPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 8.25pt")]
        public global::System.Drawing.Font DescriptiveTextFont {
            get {
                return ((global::System.Drawing.Font)(this["DescriptiveTextFont"]));
            }
            set {
                this["DescriptiveTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 8.25pt")]
        public global::System.Drawing.Font ValuesTextFont {
            get {
                return ((global::System.Drawing.Font)(this["ValuesTextFont"]));
            }
            set {
                this["ValuesTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 8.25pt")]
        public global::System.Drawing.Font TimeTextFont {
            get {
                return ((global::System.Drawing.Font)(this["TimeTextFont"]));
            }
            set {
                this["TimeTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HornSoundPath {
            get {
                return ((string)(this["HornSoundPath"]));
            }
            set {
                this["HornSoundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BuzzerSoundPath {
            get {
                return ((string)(this["BuzzerSoundPath"]));
            }
            set {
                this["BuzzerSoundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PeriodSoundPath {
            get {
                return ((string)(this["PeriodSoundPath"]));
            }
            set {
                this["PeriodSoundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BreakSoundPath {
            get {
                return ((string)(this["BreakSoundPath"]));
            }
            set {
                this["BreakSoundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeoutSoundPath {
            get {
                return ((string)(this["TimeoutSoundPath"]));
            }
            set {
                this["TimeoutSoundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Video1Path {
            get {
                return ((string)(this["Video1Path"]));
            }
            set {
                this["Video1Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Video2Path {
            get {
                return ((string)(this["Video2Path"]));
            }
            set {
                this["Video2Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Video3Path {
            get {
                return ((string)(this["Video3Path"]));
            }
            set {
                this["Video3Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Video4Path {
            get {
                return ((string)(this["Video4Path"]));
            }
            set {
                this["Video4Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayHornOnGoal {
            get {
                return ((bool)(this["PlayHornOnGoal"]));
            }
            set {
                this["PlayHornOnGoal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayHornOnStart {
            get {
                return ((bool)(this["PlayHornOnStart"]));
            }
            set {
                this["PlayHornOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayHornOnStop {
            get {
                return ((bool)(this["PlayHornOnStop"]));
            }
            set {
                this["PlayHornOnStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayBuzzerOnGoal {
            get {
                return ((bool)(this["PlayBuzzerOnGoal"]));
            }
            set {
                this["PlayBuzzerOnGoal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayBuzzerOnStart {
            get {
                return ((bool)(this["PlayBuzzerOnStart"]));
            }
            set {
                this["PlayBuzzerOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayBuzzerOnStop {
            get {
                return ((bool)(this["PlayBuzzerOnStop"]));
            }
            set {
                this["PlayBuzzerOnStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayOnPeriodChange {
            get {
                return ((bool)(this["PlayOnPeriodChange"]));
            }
            set {
                this["PlayOnPeriodChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayBreakStart {
            get {
                return ((bool)(this["PlayBreakStart"]));
            }
            set {
                this["PlayBreakStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayBreakEnd {
            get {
                return ((bool)(this["PlayBreakEnd"]));
            }
            set {
                this["PlayBreakEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayTimeoutStart {
            get {
                return ((bool)(this["PlayTimeoutStart"]));
            }
            set {
                this["PlayTimeoutStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayTimeoutEnd {
            get {
                return ((bool)(this["PlayTimeoutEnd"]));
            }
            set {
                this["PlayTimeoutEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontScore {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FontScore"]));
            }
            set {
                this["FontScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontShots {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FontShots"]));
            }
            set {
                this["FontShots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontGameTime {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FontGameTime"]));
            }
            set {
                this["FontGameTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontPenaltyTime {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FontPenaltyTime"]));
            }
            set {
                this["FontPenaltyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontPenaltyNumber {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FontPenaltyNumber"]));
            }
            set {
                this["FontPenaltyNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontPeriod {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FontPeriod"]));
            }
            set {
                this["FontPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontDescSmall {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FontDescSmall"]));
            }
            set {
                this["FontDescSmall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontDescLarge {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FontDescLarge"]));
            }
            set {
                this["FontDescLarge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontTeamName {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FontTeamName"]));
            }
            set {
                this["FontTeamName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public double FontScoreSize {
            get {
                return ((double)(this["FontScoreSize"]));
            }
            set {
                this["FontScoreSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
        public double FontShotsSize {
            get {
                return ((double)(this["FontShotsSize"]));
            }
            set {
                this["FontShotsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double FontGameTimeSize {
            get {
                return ((double)(this["FontGameTimeSize"]));
            }
            set {
                this["FontGameTimeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double FontPenaltyTimeSize {
            get {
                return ((double)(this["FontPenaltyTimeSize"]));
            }
            set {
                this["FontPenaltyTimeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double FontPenaltyNumberSize {
            get {
                return ((double)(this["FontPenaltyNumberSize"]));
            }
            set {
                this["FontPenaltyNumberSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double FontPeriodSize {
            get {
                return ((double)(this["FontPeriodSize"]));
            }
            set {
                this["FontPeriodSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double FontDescSmallSize {
            get {
                return ((double)(this["FontDescSmallSize"]));
            }
            set {
                this["FontDescSmallSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double FontDescLargeSize {
            get {
                return ((double)(this["FontDescLargeSize"]));
            }
            set {
                this["FontDescLargeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public double FontTeamNameSize {
            get {
                return ((double)(this["FontTeamNameSize"]));
            }
            set {
                this["FontTeamNameSize"] = value;
            }
        }
    }
}
